version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schoolSystem
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=1
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=fYYeVOXFBx9Qs3KfFxSeV674tqEVTr38
      - DRIVE_DISK=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=lucid
      - DB_PASSWORD=my-secret-pw
      - DB_DATABASE=school
      - CACHE_VIEWS=false
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: node ace serve --watch
    networks:
      - my-network

  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=school
      - MYSQL_USER=lucid
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
