version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schoolSystem
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=lucid
      - DB_PASSWORD=my-secret-pw
      - DB_DATABASE=lucid
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    command: node ace serve --watch

  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydatabase
    ports:
      - "3306:3306"
